aluguel_de_carros/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('carros/', include(('carros.urls'), namespace='carros')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carros/urls.py
from django.urls import path
from .views import alugando_carro, carros_alugados, devolver_carro

app_name = 'carros'

urlpatterns = [
    path('carro_form/<int:pk>/', alugando_carro, name='carro_form'),
    path('carros_alugados/', carros_alugados, name='carros_alugados'),
    path('devolver_carro/<int:pk>/', devolver_carro, name='devolver_carro'),
]

carros/models.py
from django.db import models
from stdimage.models import StdImageField
import uuid

from usuarios.models import CustomUser


# Create your models here.

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'

    return filename


class Carros(models.Model):

    placa = models.CharField('Placa do carro', max_length=9)
    marca = models.CharField('Marca do carro', max_length=140)
    modelo = models.CharField('Modelo do carro', max_length=140)
    ano = models.IntegerField('Ano do carro')
    cor = models.CharField('Cor do carro', max_length=140)
    quilometragem = models.IntegerField('Quilometragem do carro')
    valor_diario = models.DecimalField('Valor da diária', max_digits=8, decimal_places=2)
    imagem = StdImageField('Imagem', upload_to=get_file_path, variations={'thumb':{'width':400, 'height':480, 'crop':True}})


    def __str__(self):
        return f'{self.marca} {self.modelo} {self.ano}'


class AluguelCarro(models.Model):
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    carro = models.ForeignKey(Carros, on_delete=models.CASCADE)
    quantidade_dias = models.IntegerField(default=1)


    def calcular_valor_aluguel(self):
        return self.quantidade_dias * self.carro.valor_diario
    

    def __str__(self):

        return f'{self.usuario.cpf} {self.carro.marca} {self.carro.modelo} {self.carro.valor_diario}'
 

carros/forms.py
from django import forms
from django.forms import ModelForm
from .models import AluguelCarro


class ReservandoCarro(ModelForm):

    class Meta:
        model = AluguelCarro
        fields = ['quantidade_dias']

carros/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Carros, AluguelCarro
from .forms import ReservandoCarro
# Create your views here.


@login_required(login_url='login_page')
def alugando_carro(request, pk):

    if request.method == 'POST':
        form = ReservandoCarro()

        carro = Carros.objects.get(id=pk)
        modelo = carro.modelo
        quantidade_dias = request.POST.get('quantidade_dias')

        try:
            carro_alugado = AluguelCarro(
                usuario = request.user,
                carro = carro,
                quantidade_dias = quantidade_dias

            )
            carro_alugado.save()
            messages.success(request, f'O carro {modelo} foi alugado com sucesso.')
            return redirect('carros:carros_alugados')
        except ValueError as err:
            messages.error(request, f'Erro: {err}')
            return redirect('home')
    else:
        form = ReservandoCarro()

    return render(request, 'carro_form.html', {'form': form})    


@login_required(login_url='login_page')
def carros_alugados(request):
    carro_alugado = AluguelCarro.objects.filter(usuario=request.user)

    return render(request, 'carros_alugados.html', {'carros': carro_alugado})


@login_required(login_url='login_page')
def devolver_carro(request, pk):
    carro_alugado = AluguelCarro.objects.get(id=pk, usuario=request.user)

    if request.method == 'POST':
        quilometragem_rodada = int(request.POST.get('quilometragem_rodada'))
        carro = carro_alugado.carro
        carro.quilometragem += quilometragem_rodada
        carro.save()


        carro_alugado.delete()
        messages.success(request, f'O carro {carro.modelo} foi devolvido com sucesso.')
        return redirect('carros:carros_alugados')
    
    return render(request, 'carros_alugados.html')

carros/templates/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AkugaAi</title>
    {% bootstrap_css %}
</head>
<body>
    <div class="container mt-5  ">
        {% block content %} {% endblock %}
    </div>
    {% bootstrap_javascript %}
</body>
</html>

carros/templates/carro_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    {% bootstrap_messages %}

    <form method="POST">
        {% csrf_token %}
        
        {% bootstrap_form form %}

        {% buttons %}
           <button class="btn btn-primary" type="submit" name="confirmar_aluguel">Confirmar</button>

        {% endbuttons %}
    </form>

</div>

{% endblock %}

carros/templates/carros_alugados.html
{% extends 'base.html'%}
{% load bootstrap5 %}

{% block content %}

<div class="container">
    {% bootstrap_messages %}

    {% if carros %}
        {% for carro in carros %}
            <div class="row">


                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img src="{{carro.carro.imagem.url}}" class="card-img-top" alt="carro_generico">
                        <div class="card-body">
                            <h5 class="card-title">Marca: {{carro.carro.marca}}</h5>
                            <p class="card-text">Modelo: {{carro.carro.modelo}}</p>
                            <p class="card-text">Ano: {{carro.carro.ano}}</p>
                            <p class="card-text">Cor: {{carro.carro.cor}}</p>
                            <p class="card-text">Quilometragem: {{carro.carro.quilometragem}}</p>
                            <p class="card-text">Valor diário: {{carro.carro.valor_diario}}</p>
                        </div>
                        <div class="card-footer d-flex" style="margin-left: 2px;">
                            <form method="POST" action="{% url 'carros:devolver_carro' carro.id %}">
                                {% csrf_token %}

                                <div class="form-group">
                                    <input type="number" class="form-control" name="quilometragem_rodada" placeholder="Quilometragem rodada" required>
                                </div>
                                <p class="mb-3">Valor a pagar: R${{carro.calcular_valor_aluguel}}</p>
                                <div style="margin-left: 120px;">
                                    {% buttons %}
                                       <button class="btn btn-primary" type="submit" name="devolver_carro">Devolver</button>
                                    {% endbuttons %}
                                </div>
                            </form>
                        </div>
                    </div>  
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>Ainda não há carros alugados.</p>
    {% endif %} 

</div>

{% endblock %}