aluguel_de_carros/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('carros/', include(('carros.urls'), namespace='carros')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carros/urls.py
from django.urls import path
from .views import alugando_carro, carros_alugados, devolver_carro

app_name = 'carros'

urlpatterns = [
    path('carro_form/<int:pk>/', alugando_carro, name='carro_form'),
    path('carros_alugados/', carros_alugados, name='carros_alugados'),
    path('devolver_carro/<int:pk>/', devolver_carro, name='devolver_carro'),
]

usuarios/urls.py
from django.urls import path
from .views import home, criar_usuario, login_page, logout_page, perfil_page, atualizar_dados, atualizar_senha, deletar_usuario

urlpatterns = [
    path('', home, name='home'),
    path('form_usuario/', criar_usuario, name='criar_usuario'),
    path('login_page/', login_page, name='login_page'),
    path('logout_page/', logout_page, name='logout_page'),
    path('perfil_page/', perfil_page, name='perfil_page'),
    path('atualizar_dados/', atualizar_dados, name='atualizar_dados'),
    path('atualizar_senha/', atualizar_senha, name='atualizar_senha'),
    path('deletar_conta/', deletar_usuario, name='deletar_usuario'),
]

usuarios/models.py
from django.db import models

# Create your models here.
# QUANDO FOR CRIAR UM USUÁRIO CUSTOMIZADO...CRIE O MODELO E DEPOIS CRIE AS MIGRAÇÕES QUE O DJANGO UTILIZA!!!
from django.contrib.auth.models import AbstractUser, BaseUserManager

    
class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('É necessário informar um e-mail!')
        email = self.normalize_email(email) # realiza a validação se p valor informado é um email verdadeiro.
        user = self.model(email=email, username=email, **extra_fields) 
        user.set_password(password) # criptografa a semha.
        user.save(using=self._db) # salva no banco de dados
        return user # retorna o usuário
    
    
    def create_user(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', False) # o valor "is_superuser" fica recebe o valor False
        return self._create_user(email, password, **extra_fields) # Retorna o usuário não super usuário.
    

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('is_staff precisa ser True')
       
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('is_superuser precisa ser True')
        
        return self._create_user(email, password, **extra_fields)

class CustomUser(AbstractUser):
    email = models.EmailField('e-mail', unique=True)
    nome = models.CharField('nome', max_length=200)
    sobrenome = models.CharField('sobrenome', max_length=200)
    cpf = models.CharField('cpf', max_length=11)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome', 'sobrenome']

    def __str__(self):
        return self.email
    
    objects = UserManager()

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, SetPasswordForm
from .models import CustomUser

# Criar usuários junto com senha.
class CustomUserCreateForm(UserCreationForm):

    class Meta:
        model = CustomUser

        labels = {'username':'E-mail'}
        fields = ['email', 'nome', 'sobrenome', 'cpf']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user
    

# Editar usuários (exceto senhas)
class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        
        fields = ['email', 'nome', 'sobrenome', 'cpf']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Remove o campo de senha completamente
        if 'password' in self.fields:
            del self.fields['password']
        


class CustomLoginPage(AuthenticationForm):
    username = forms.EmailField(label='E-mail')
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser


class PasswordUserChange(SetPasswordForm):
    new_password1 = forms.CharField(label='Nova senha', widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='Confirmar Nova Senha', widget=forms.PasswordInput)


    class Meta:
        fields = ['new_password1', 'new_password2']

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .forms import CustomUserCreateForm, CustomLoginPage, CustomUserChangeForm, PasswordUserChange
from .models import CustomUser
from carros.models import Carros
# Create your views here.


def home(request):
    carros = Carros.objects.all()

    return render(request, 'home.html', {'carros': carros})


def criar_usuario(request):
    
    form = CustomUserCreateForm()

    if request.method == 'POST':
        form = CustomUserCreateForm(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            user.username = user.email.lower()
            user.save()
            
            login(request, user)
            return redirect('home')
    
    return render(request, 'form_usuario.html', {'form': form})


# Sempre tenha uma view function login_page para que os usuários sejam autenticado e apareçam no template.
def login_page(request):

    if request.method == 'POST':
        form = CustomLoginPage(request, data=request.POST)

        if form.is_valid():

            email = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=email, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = CustomLoginPage()
    
    return render(request, 'login_page.html', {'form': form})


@login_required(login_url='login_page')
def atualizar_dados(request):

    form = CustomUserChangeForm(instance=request.user)

    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)

        if form.is_valid():

            form.save()
            messages.info(request, 'Dados atualizados com sucesso!')
            return redirect('perfil_page')

    return render(request, 'atualizar_dados.html', {'form':form})


@login_required(login_url='login_page')
def atualizar_senha(request):

    if request.method == 'POST':
        form = PasswordUserChange(user=request.user, data=request.POST)
        
        if form.is_valid():

            user = form.save()
            update_session_auth_hash(request, user)
            
            messages.info(request, 'Senha atualizada com sucesso!')
            return redirect('perfil_page')
    else:
        form = PasswordUserChange(user=request.user)

    
    return render(request, 'atualizar_senha.html', {'form': form})


@login_required(login_url='login_page')
def deletar_usuario(request):
    
    user = CustomUser.objects.get(username=request.user.username)

    if request.method == 'POST':
        user.delete()
        
        messages.info(request, 'Conta apagada com sucesso!')

        return redirect('home')
    return render(request, 'deletar_usuario.html')


@login_required(login_url='login_page')
def logout_page(request):

    logout(request)
    return redirect('home')


@login_required(login_url='login_page')
def perfil_page(request):

    user = CustomUser.objects.filter(username=request.user)

    return render(request, 'perfil_page.html', {'user': user})

usuarios/templates/atualizar_dados.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">

    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}

        <a href="{% url 'atualizar_senha' %}">Atualizar senha</a>
        {% buttons %}
            <button class="btn btn-primary" type="submit" name="atualizar_dados">Atualizar</button>
        {% endbuttons %}
    </form>
</div>

{% endblock %}

usuarios/templates/atualizar_senha.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div class="container">
    
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button class="btn btn-primary" type="submit" name="nova_senha">Atualizar</button>
        {% endbuttons %}
    </form>
</div>

{% endblock %}

usuarios/templates/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AkugaAi</title>
    {% bootstrap_css %}
</head>
<body>

    <header>
      {% if request.path != '/login_page/' and request.path != '/form_usuario/' and  request.path != '/logout_page/' and request.path != '/deletar_conta/' and request.path != '/perfil_page/' and request.path != '/atualizar_dados/' and request.path != '/atualizar_senha/'%}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">AlugaAi</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'carros:carros_alugados' %}">Carros alugados</a>
                    </li>
                  </ul>
                </div>
                
                <div>
                    {% if user.is_authenticated %}
                        <h3>Seja Bem-Vindo, {{user.nome}} {{user.sobrenome}}</h3>
                        <a href="{% url 'logout_page' %}">Logout</a>
                        <a href="{% url 'perfil_page' %}">Perfil</a>
                    {% else %}
                        <a href="{% url 'login_page' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </nav>
      {% endif %}
    </header>
    <div class="container mt-5  ">
        {% block content %} {% endblock %}
    </div>
    {% bootstrap_javascript %}
</body>
</html>

usuarios/templates/deletar_usuario.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div class="container" style="justify-content: center;">

    <form method="POST">
        {% csrf_token %}

        <p>Tem certeza que deseja apagar a conta: <strong>{{request.user.nome}} {{request.user.sobrenome}}<strong>?</p>

        {% buttons %}
            <a href="{% url 'perfil_page' %}" class="btn btn-warning">Cancelar</a>
            <button class="btn btn-primary" type="submit" name="confimar">Continuar</button>
        {% endbuttons %}

    </form>

</div>
{% endblock %}

usuarios/templates/form_usuario.html
{% extends 'home.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}

        {% bootstrap_form form %}

        {% buttons %}
            <button class="btn btn-primary" type="submit">Enviar</button>
        {% endbuttons %}

    </form>
</div>
{% endblock %}

usuarios/templates/home.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<div class="container">
    {% bootstrap_messages %}

    {% if carros %}
        {% for carro in carros %}
        
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img src="{{carro.imagem.url}}" class="card-img-top" alt="carro_generico">
                    <div class="card-body">
                        <h5 class="card-title">Marca: {{carro.marca}}</h5>
                        <p class="card-text">Modelo: {{carro.modelo}}</p>
                        <p class="card-text">Ano: {{carro.ano}}</p>
                        <p class="card-text">Cor: {{carro.cor}}</p>
                        <p class="card-text">Quilometragem: {{carro.quilometragem}}</p>
                        <p class="card-text">Valor diário: {{carro.valor_diario}}</p>
                    </div>
                    <div style="margin-left: 120px;">
                        {% buttons %}
                           <a href="{% url 'carros:carro_form' carro.id %}"><button class="btn btn-primary" type="submit">Alugar</button></a>
                        {% endbuttons %}
                    </div>
                </div>  
            </div>
        </div>
        {% endfor %}

    {% else %}
        <li>Não há carros cadastrados no momento</li>
    {% endif %}
</div>

{% endblock %}

usuarios/templates/login_page.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">

    <h1>Login Page</h1>

    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
           <button class="btn btn-primary" type="submit">Enviar</button>
        {% endbuttons %}
    </form>
    <p>Ou crie sua conta: <a href="{% url 'criar_usuario' %}">Cadastro</a></p>
</div>

{% endblock %}

usuarios/templates/perfil_page.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container">
    {% bootstrap_messages %}
    <p>Nome: {{request.user.nome}} {{request.user.sobrenome}}</p>
    <p>E-mail: {{request.user.email}}</p>
    <p>CPF: {{request.user.cpf}}</p>

    <a href="{% url 'atualizar_dados' %}">Atualizar dados</a>
    <a href="{% url 'deletar_usuario' %}">Apagar Conta</a>
</div>

{% endblock %}